# Generated by Django 4.2.23 on 2025-08-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("Cricket", "Cricket"),
                            ("Football", "Football"),
                            ("Badminton", "Badminton"),
                            ("Running", "Running"),
                            ("Gym", "Gym"),
                            ("Cycling", "Cycling"),
                            ("Swimming", "Swimming"),
                            ("Kabaddi", "Kabaddi"),
                            ("Yoga", "Yoga"),
                            ("Basketball", "Basketball"),
                            ("Chess", "Chess"),
                            ("Table Tennis", "Table Tennis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Corporate", "Corporate"),
                            ("School", "School"),
                            ("College/University", "College/University"),
                            ("Club/Academy", "Club/Academy"),
                            ("District", "District"),
                            ("State", "State"),
                            ("Zonal/Regional", "Zonal/Regional"),
                            ("National", "National"),
                            ("International", "International"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("official_url", models.URLField()),
                ("streaming_links", models.URLField(blank=True, null=True)),
                ("tournament_image", models.URLField(blank=True, null=True)),
                ("summary", models.TextField(max_length=50)),
            ],
        ),
    ]
