# Generated by Django 4.2.23 on 2025-08-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="summary",
            field=models.TextField(max_length=300),
        ),
    ]
